spring:
  kafka:
    bootstrap-servers:
    - localhost:9092
    consumer:
      group-id: test
      enable-auto-commit: true
      auto-commit-interval: 1000
      auto-offset-reset: earliest
      client-id: test