server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  profiles:
    active: dev
  application:
    name: ws
  resources:
    add-mappings: false
    static-locations: classpath:/static/,classpath:/templates/index/
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8


#配置日志
logging:
  #配置日志文件路径
  path: /log
  pattern:
    console: "%d - %msg%n"
    level:
      com.arc: debug #不同目录下的日志可配置不同级别
      org.springfromework.web: debug


---
spring:
  profiles: dev


